"""tambah kolom google_id

Revision ID: fc59b7757f5d
Revises: 
Create Date: 2026-01-21 22:42:45.176395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc59b7757f5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=255), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.create_unique_constraint(None, ['google_id'])

    with op.batch_alter_table('wayang_game', schema=None) as batch_op:
        batch_op.alter_column('thumbnail',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('badan',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('tangan_kanan_atas',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('tangan_kanan_bawah',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('tangan_kiri_atas',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('tangan_kiri_bawah',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wayang_game', schema=None) as batch_op:
        batch_op.alter_column('tangan_kiri_bawah',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('tangan_kiri_atas',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('tangan_kanan_bawah',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('tangan_kanan_atas',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('badan',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('thumbnail',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('google_id')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    # ### end Alembic commands ###
